### ISSUE TITLE
Update for new versions of Sensu

### ISSUE THREAD

**Issue by davidmc24** [commercehub-oss/sensu-java-api#1]
Since this was last updated, Sensu has released several new versions, and some of them included API changes.  Check the latest API docs, and add support as needed.

Since different versions of Sensu support different APIs (introducing breaking changes at points) we'll at a minimum want to document what version of the API each library version supports.

https://sensuapp.org/docs/0.25/api-overview

**Comment by efalkner** [comment]
Updated to accommodate existing behaviors in #19 . Covering additional functionality, like new features in Sensu, will be treated as a follow on change set.
