### ISSUE TITLE
Any plans to support new version 0.29?

### ISSUE THREAD

**Issue by mohanrao** [commercehub-oss/sensu-java-api#20]
Hi,

Are there any plans to support the new version of 0.29?

**Comment by davidmc24** [comment]
We're likely going to be upgrading our Sensu deployment to Sensu 1.x sometime in 2018 Q2, and likely will update this library's compatibility prior to that.  If you have specific needs prior to that, we're open to pull requests.

**Comment by mohanrao** [comment]
Glad to hear that. I cloned the repo. I will start working on upgrading the library. I want to use add results api endpoint functionality. 

Also, I realized the gradle and other open source libraries versions needs to upgrade

**Comment by davidmc24** [comment]
Both updates to the version of gradle and versions of the open source libraries used would be changes I'm open to.  If you pursue a pull request, please constrain it to just one type of change at a time (for example, just upgrading gradle version, or just upgrading versions of dependencies, or just updating API compatibility) to facilitate easier review.

**Comment by mohanrao** [comment]
Agree. Will try to work in that way in coming days

**Comment by davidmc24** [comment]
This project has been deprecated, and will see no further updates.  Please feel free to fork if it's still useful to you.
