### ISSUE TITLE
Add a CI badge to readme

### ISSUE THREAD

**Issue by davidmc24** [commercehub-oss/sensu-java-api#9]
It looks like this project is using Travis CI for continuous integration, but there isn't any mention in the README of it.  Someone first coming to the project would better be able to judge its current state if the following badge were added to the readme:

`[![Build Status](https://travis-ci.org/commercehub-oss/sensu-java-api.svg?branch=master)](https://travis-ci.org/commercehub-oss/sensu-java-api)`

https://travis-ci.org/commercehub-oss/sensu-java-api

**Comment by efalkner** [comment]
Updated in #10
